repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/prospector
    rev: 1.3.0 # The version of Prospector to use, at least 1.1.7
    hooks:
      - id: prospector
        exclude: ^tests/
  -   repo: https://github.com/PyCQA/bandit
      rev: '1.6.2'
      hooks:
      - id: bandit
        language_version: python3
        exclude: ^tests/
        args:
        - -c
        - bandit.yml
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.782'
      hooks:
      -   id: mypy
          args: [--ignore-missing-imports]
          exclude: ^(tests/|turbulette/core/management/templates)
          additional_dependencies: [ariadne==0.12.0]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
