repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: prospector
        name: prospector
        entry: prospector
        language: system
        types: [python]
        exclude: ^(tests/|turbulette/management/templates/|docs/)
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
