dist: xenial
language: python
python:
- 3.8
- 3.6
- 3.7
stages:
- test
- name: deploy
  if: tag IS present

# Tests
before_install:
- pip install poetry
install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)/turbulette
- poetry install --no-root -v
services:
- postgresql
env:
  - DB_DRIVER=postgresql DB_HOST=localhost DB_PORT=5432 DB_USER=postgres DB_PASSWORD=""
    PYTEST_TURBULETTE_SETTINGS=tests.settings
before_script:
- psql -c 'create database test;' -U postgres
script:
  - pytest --ignore ./tests/turbulette_tests/cli
  - pytest ./tests/turbulette_tests/cli

jobs:
  include:
    - stage: deploy
      script: skip
      before_deploy:
        - pip install --upgrade pip
        - pip install poetry
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
      deploy:
        provider: script
        script: poetry publish --build
        on:
          tags: true
          repo: gazorby/turbulette


after_success:
- bash <(curl -s https://codecov.io/bash)
