[tool.poetry]
name = "turbulette"
version = "0.1.0"
description = "An async Python GraphQL framework built on top of Ariadne and GINO"
authors = ["Gazorby <gazorby@pm.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
gunicorn = "^20.0.4"
ariadne = "^0.11.0"
pydantic = {extras = ["email"], version = "^1.6.1"}
uvicorn = "^0.11.5"
alembic = "^1.4.2"
psycopg2-binary = "^2.8.5"
gino = {extras = ["starlette"], version = "^1.0.1"}
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
pyjwt = "^1.7.1"
requests = "^2.24.0"
starlette = "^0.13.4"
simple-settings = "^0.19.1"
gino-enum-tables = "^1.0.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
rope = "^0.17.0"
pylint = "^2.5.3"
ptvsd = "^4.3.2"
uvicorn = {extras = ["watchgodreload"], version = "^0.11.5"}
tuna = "^0.4.5"
memory_profiler = "^0.57.0"
pytest = "^6.0.1"
pytest-cov = "^2.10.0"
pytest-asyncio = "^0.14.0"

[tool.poetry.plugins."pytest11"]
"turbulette" = "turbulette.test.pytest_plugin"

[tool.pytest.ini_options]
minversion = "6.0"
# addopts = "--cov=turbulette --cov-report html"
# --cov-report xml
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
