name: CD
on:
  push:
    branches:
      - main
      - ci/*
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout source code
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v2
      - name: Set up Python
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          python get-poetry.py -y
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Build Python package and publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}

  build-docs:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
      - uses: actions/setup-python@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          python-version: 3.9
      - run: pip install mkdocs-material mkdocs-git-revision-date-plugin mkdocstrings pygments-graphql-lexer pymdown-extensions
      - run: mkdocs gh-deploy --force
