# Adapted from https://github.com/python-gino/gino/blob/master/.github/workflows/test.yml

name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      # - name: Set up Poetry cache for Python dependencies
      #   uses: actions/cache@v2.1.4
      #   if: startsWith(runner.os, 'Linux')
      #   with:
      #     path: ~/.cache/pypoetry
      #     key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('**/poetry.lock') }}
      #     restore-keys: ${{ runner.os }}-${{ matrix.python-version }}-poetry-
      - name: virtualenv cache
        uses: syphar/restore-virtualenv@v1.1
      - name: Install poetry
        run: bash ./scripts/install-poetry.sh
      - name: Install dependencies
        run: poetry install --no-interaction --no-root -E dev_test -E dev_lint -E dev_doc
      - name: List installed packages
        run: poetry show
      - name: test
        env:
          DB_DRIVER: postgresql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: ""
          TURBULETTE_SETTINGS_MODULE: tests.settings
        run: export PYTHONPATH=$PYTHONPATH:$(pwd)/turbulette && make testcov-xml
      - name: lint
        run: |
          poetry run black --check .
          poetry run mypy turbulette --ignore-missing-imports
      - name: coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: coverage.xml
